language: python
python:
  - 3.8.0
install:
  - pip install -q -r requeriments-dev.txt codecov
  - pip install pytest-mock
script:
  - flake8
  - pytest
  - pytest --cov=prj_libpythonpro
after_success:
  -codecov
